"""pushups table

Revision ID: a2ee16cc4335
Revises: a3c8afdb6ef1
Create Date: 2025-10-22 10:56:04.282415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ee16cc4335'
down_revision = 'a3c8afdb6ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pushup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pushup_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_pushup_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pushup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pushup_user_id'))
        batch_op.drop_index(batch_op.f('ix_pushup_timestamp'))

    op.drop_table('pushup')
    # ### end Alembic commands ###
